---
deployment:
  tasks:
    - export DEPLOYPATH="/home/$USER/"
    - /bin/cp -R app ${DEPLOYPATH}
    - /bin/cp -R bootstrap ${DEPLOYPATH}
    - /bin/cp -R config ${DEPLOYPATH}
    - /bin/cp -R database ${DEPLOYPATH}
    - /bin/cp -R public ${DEPLOYPATH}
    - /bin/cp -R resources ${DEPLOYPATH}
    - /bin/cp -R routes ${DEPLOYPATH}
    - /bin/cp -R tests ${DEPLOYPATH}
    - /bin/cp artisan ${DEPLOYPATH}
    - /bin/cp composer.json ${DEPLOYPATH}
    - /bin/cp package.json ${DEPLOYPATH}
    - /bin/php ${DEPLOYPATH}artisan cache:clear
    - /bin/php ${DEPLOYPATH}artisan config:clear
    - /bin/php ${DEPLOYPATH}artisan route:clear
    - /bin/php ${DEPLOYPATH}artisan view:clear
    - /bin/php ${DEPLOYPATH}composer.phar dumpautoload
